Initial upload of HTML for GitHub Pages
amd/aocl-compression pull request #1
Opened 2024-04-23 17:33 UTC by ryanvergel

2024-04-25 07:18 UTC, BiplabRaut requested changes
I have a comment. Can you please respond.

2024-04-25 07:18 UTC, BiplabRaut commented on LICENSE.txt
> +THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMEN
This is the main license file that is for the entire library. 
I see that the BSD license is replaced with the MIT license, and it talks about both the software and documentation distribution.
Why is the main license modified ?
Was there any discussion on the license thing?
If it is needed only for the html and documentation, then should this license file be not placed in the doc folder ?

2024-05-01 16:34 UTC, ryanvergel commented
Hi @BiplabRaut , I have removed the superfluous `LICENSE.txt` file :)

2024-05-02 18:01 UTC, BiplabRaut commented
> Hi @BiplabRaut , I have removed the superfluous `LICENSE.txt` file :)

Hi Ryan,
I see that you have now deleted the License file. But this file was the library level single master license file.
Are we not supposed to maintain the LICENSE info in the library level for the documentation?

2024-05-06 09:05 UTC, BiplabRaut approved these changes

2024-05-06 09:06 UTC, merged